#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=breeze_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=''
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=None
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=none
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='eDP-1=1.6;DP-1=1.6;HDMI-1=1.6;DP-2=1.6;HDMI-2=1.6;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=154
